CC=g++
PRE=-std=c++98 

all:
	$(CC) $(PRE) main.cpp AND.cpp Connect.cpp Connections.cpp Logic.cpp LogicsTable.cpp NAND.cpp NOR.cpp NOT.cpp OR.cpp PlotCreator.cpp Scheduler.cpp SimCore.cpp -o sim



clean:							# smazani nezadoucich souboru
	rm -f *~
	rm -f *.o
	rm -f sim
	rm -f *.dat
	rm -f *.plt

